//
//  YapModelViewProvider.h
//
//  Created by Aleksei Shevchenko on 6/17/15.
//

#import <Foundation/Foundation.h>

@class YapDatabase;

/**
 *  YapModelViewProvider simply generates any additional views, that cannot be generated by DSL
 */
@protocol YapModelViewProvider

/**
 *  Create any views that cannot be created using DSL (some special groupping/soting for example)
 *
 *  @param database YapDatabase instance
 */
+(void) registerViewsWithDatabase:(YapDatabase*)database;

@end
